### ISSUE TITLE
Set vars from project.clj

### ISSUE THREAD

**Issue by rosejn** [jarohen/nomad#19]
We use nomad everywhere with great success, but one addition that would be helpful is to support setting configuration vars on a per profile basis in the project.clj.  The environ library does this well by using a leiningen plugin, but it doesn't have the nice config file functionality of nomad.  For now I'll use both, but it seems like with this addition nomad would be the only needed config/environment related library.

**Comment by james-henderson** [comment]
Hi Jeff,

One solution I've thought about for this for a while (but wasn't sure if anyone would use!) is if Nomad could pull through JVM system properties into the config map, in a similar way to environment variables - these could be set in your project.clj, and overridden in the various profiles. The benefits of this would also be that we wouldn't need a separate lein plugin and that, if the project was built, deployed and run without Leiningen, config could still be passed as '-D' parameters. Would this work for your use case?

James

**Comment by james-henderson** [comment]
Just deployed 0.7.1-SNAPSHOT, with this change - you can refer to a JVM property as follows:

```clojure
{:config-var #nomad/jvm-prop "yourapp.property"
 :other-key "value"}
```

Let me know what you think :)

James

**Comment by rosejn** [comment]
Cool, I'll try it out.  Thanks!
