### ISSUE TITLE
Environment variables with defaults

### ISSUE THREAD

**Issue by glittershark** [jarohen/nomad#20]
It'd be really cool if the `env-var` and `edn-env-var` supported some form of defaults if those environment variables aren't set

**Comment by james-henderson** [comment]
Hi Griffin - good idea :)

I've implemented something similar for [Phoenix](https://github.com/james-henderson/phoenix) that involved the user specifying an optional extra argument - something like `#nomad/edn-env-var ["PORT" 3000]`, in addition to the current `#nomad/edn-env-var "PORT"`, maybe? This should be pretty straightforward to apply to Nomad too in the reader macro - fancy submitting a PR? ;)

James

**Comment by SevereOverfl0w** [comment]
The related PR for this issue has been closed, does that mean this feature is part of Nomad now?

I'm not seeing it in the docs.
