### ISSUE TITLE
add #nomad/env-format

### ISSUE THREAD

**Issue by martintrojer** [jarohen/nomad#23]
Very useful to be able to construct strings inside a config file.

```
#nomad/env-format ["http://%s:%s/api/1.0" API_HOST API_PORT]
```

See `#envf` here;

https://github.com/juxt/joplin#hiding-secrets-from-the-configuration-map

**Comment by jarohen** [comment]
Hi Martin, yes - agreed!

If Joplin calls it #envf, I'm happy to call it #nomad/envf too. I'm afraid I don't have a lot of time outside work at the moment, so it might be a while coming, unless you could submit a PR?

Cheers,

James

**Comment by martintrojer** [comment]
raised a PR.

called in env-format since I though it was more in line with existing nomad reader tags
