### ISSUE TITLE
Application does not exit after invoking the function returned from defconfig

### ISSUE THREAD

**Issue by JGailor** [jarohen/nomad#30]
Using the hello world example provided, after I invoke the function returned from defconfig my application gets to the end of -main and then does not exit.  I couldn't find anything in the documentation mentioning this behaviro, so I'm not sure if it's a bug or a misunderstanding on my part.

**Comment by jarohen** [comment]
Hi Jeremy - that's likely because either Nomad, something Nomad depends on, or something else within your application uses Clojure's agents, which prevent shutdown of the JVM for at least a minute (until the threads finish). You can stop them immediately with `(shutdown-agents)`

HTH!

James

**Comment by JGailor** [comment]
Ahhh.  Thanks.  I was using Nomad to configure a c3p0 pool, but did not have the delay until first invoking that function.  I read through the Nomad source code after getting suspicious about it's config file reloading, but did not see anything that looked like it was creating another thread.   Could it be the call to (io/resource "my/config/file.edn")?

**Comment by jarohen** [comment]
Hmm - if it was I'd be surprised - think that's completely synchronous, and single-threaded?
