### ISSUE TITLE
get-hostname slow on MacOS Sierra

### ISSUE THREAD

**Issue by brandondtb** [jarohen/nomad#33]
#32 changed hostname resolution to `(.. java.net.InetAddress getLocalHost getHostName)` which takes several seconds to resolve on MacOS Sierra.

The issue and an end-user fix for it are discussed [here](https://thoeni.io/post/macos-sierra-java/).

This isn't specifically a Nomad bug, but I wanted to surface it here as it effects library users running MacOS Sierra.

**Comment by jarohen** [comment]
Thanks for the heads up, Brandon!

**Comment by jarohen** [comment]
Nomad no longer switches on hosts (as of 0.9.0-rc1 - you can switch on whatever you like in client code), closing this. 

Thanks!
