### ISSUE TITLE
config dispatched on username?

### ISSUE THREAD

**Issue by malcolmsparks** [jarohen/nomad#4]
Given the opportunity, I often create Unix accounts for different environments when I'm forced to use the same host for them.

Would it be possible to dispatch on username in (optional) addition to hostname, rather than be forced to use env vars?

**Comment by jarohen** [comment]
Hey Malcolm, long time no speak! Didn't realise this one was still open.

Can now switch on whatever you like in 0.9.0-rc1, so will close this one.

If you get a mo, the rationale and implementation have changed pretty significantly, would be interested to here your thoughts :)

James
